version: "3.8"

services:
  react-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: react-container
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
